### ISSUE TITLE
PC <-> ACC instructions

### ISSUE THREAD

**Issue by Turysaz** [Turysaz/hrmvm#4]
Add instructions to change the PC dynamically.
This feature could be used to realize dynamic function calls and returns /  a call stack.

    JUMPA    ; pc = acc value
    LDPC     ; acc = pc value

## Todo

- [x] Re-evaluate opcode order
- [x] VM
    - [x] Add opcodes to code
    - [x] Add handlers to code
    - [x] Update documentation
    - [x] Unit tests
- [ ] ASM
    - [x] Add opcodes to code
    - [x] Add instruction interpretation
    - [ ] Unit tests
- [x] Update Readme.md/Modifications

**Comment by Turysaz** [comment]
Open new issue for ASM unit tests
